//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_BOOKS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Borisova_BooksEntities : DbContext
    {
        public Borisova_BooksEntities()
            : base("name=Borisova_BooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Authors> Table_Authors { get; set; }
        public virtual DbSet<Table_Books> Table_Books { get; set; }
        public virtual DbSet<Table_Genres> Table_Genres { get; set; }
        public virtual DbSet<Table_Links> Table_Links { get; set; }
    }
}
