//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_BOOKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Links
    {
        public int IdLink { get; set; }
        public string Link { get; set; }
        public int IdBook { get; set; }
    
        public virtual Table_Books Table_Books { get; set; }
    }
}
